services:
  candidat_db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=candidat'
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
    ports:
      - "${CANDIDAT_DB_PORT}"
  candidat_ms:
    image: candidat_ms:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "${SPRING_CANDIDAT_PORT}:${SPRING_CANDIDAT_PORT}"
    
