services:
  candidat_db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=Candidat_database'
    env_file: .env
    ports:
      - "${CANDIDAT_DB_PORT}"
    # volumes:
    #   - candidat_db:/data/postgres
  candidat_ms:
    image: candidat_ms:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "${SPRING_CANDIDAT_PORT}:${SPRING_CANDIDAT_PORT}"
    
